### ISSUE TITLE
Argument 2 passed to commerce_simple_stock_help() must be an instance of RouteMatchInterface

### ISSUE THREAD

**Issue by jackdaniel9** [wisamx/commerce_simple_stock#2]
Hi,

When we install the module on Drupal 8 for Commerce 2x : 

The website encountered an unexpected error. Please try again later.
TypeError: Argument 2 passed to commerce_simple_stock_help() must be an instance of RouteMatchInterface, instance of Drupal\Core\Routing\CurrentRouteMatch given in commerce_simple_stock_help() (line 8 of modules/commerce_simple_stock-master/commerce_simple_stock.module).
commerce_simple_stock_help('system.admin', Object)
call_user_func_array('commerce_simple_stock_help', Array) (Line: 391)
Drupal\Core\Extension\ModuleHandler->invoke('commerce_simple_stock', 'help', Array) (Line: 102)
Drupal\help\Plugin\Block\HelpBlock->build() (Line: 203)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array) (Line: 450)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 490)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 74)
__TwigTemplate_f8a17f041581af9829850fd45db45c2b69d8b3a60b80408d416da5d23dbccb61->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('core/themes/seven/templates/page.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('page', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 490)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 90)
__TwigTemplate_be8c7bbb9c824f2826368d7c8da984c6279779db72a67fd8056a00bb23b816f2->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('core/themes/classy/templates/layout/html.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('html', Array) (Line: 437)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 147)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 148)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 664)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by NelsNose** [comment]
I can confirm this behavior.  My fork fixes this https://github.com/NelsNose/commerce_simple_stock

**Comment by jackdaniel9** [comment]
This work with more that one product variation ?

commerce_simple_stock line.module 36 :-1: 
$variation = $product->getVariations()[0]; //My products have only one variation

If we have more than one variation, ajax add to cart form not update to show "Out of stock"

(or another solution is remove variation if stock = 0)

**Comment by jackdaniel9** [comment]
Do you know how we can get the selected variation by the user ?

**Comment by jackdaniel9** [comment]
I code this and stock work with more than one variation :

```
function commerce_simple_stock_form_commerce_order_item_add_to_cart_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_data = $form_state->getStorage();
  if (empty($form_data['product'])) {
    return;
  }
        $selectedVariationId  = $form_state->get( 'selected_variation' );
        $selectedVariation   = \Drupal\commerce_product\Entity\ProductVariation::load( $selectedVariationId );
        $field_stock= $selectedVariation->get( "field_stock" )[ 0 ];
	if ($field_stock != null) {
            
            $stock= $field_stock->getValue()[ 'value' ];
            if ($stock <= 0) {
                    $form['quantity'] = null;
                    $form['actions'] = null;
                    $form['outofstock'] = [
                      'element1' => [
                        '#type' => 'container',
                        '#attributes' => [
                            'class' => 'out-of-stock',
                        ],
                      ],
                      'element2' => [
                        '#type' => 'markup',
                        '#markup' => "Out of stock",
                        ],
                    ];
            } else {
                $form['outofstock']= [
                    'element2' => [
                      '#prefix' => '<div class="quantity">',
                      '#suffix' => '</div>',
                      '#type' => 'markup',
                      '#markup' => $stock." in stock ",
                      ],
                  ];
            }
	}
	
}
```

**Comment by wisamx** [comment]
thanks for the fix
it seems working
